# Generated by Django 3.1.1 on 2020-09-19 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tutor', models.IntegerField(max_length=100)),
                ('student', models.IntegerField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('pay_per_hour', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('card_number', models.IntegerField(blank=True, null=True)),
                ('user_status', models.IntegerField(choices=[(1, 'Teacher'), (2, 'Student/Parents')], max_length=1)),
            ],
        ),
    ]
