# Generated by Django 3.1.1 on 2020-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200920_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
