# Generated by Django 3.1.1 on 2020-10-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thurssday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='pay_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='catalog.user'),
        ),
        migrations.AlterField(
            model_name='class',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_class', to='catalog.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Student/Parents')]),
        ),
    ]
