# Generated by Django 3.1.1 on 2020-10-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201024_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_day',
        ),
        migrations.RemoveField(
            model_name='class',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_time',
        ),
        migrations.AddField(
            model_name='class',
            name='class_serial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='topic',
            field=models.CharField(blank=True, choices=[('mth', 'Math'), ('chn', 'Chinese'), ('eng', 'English'), ('geo', 'Geography'), ('his', 'History'), ('cvc', 'Civics'), ('scl', 'Social'), ('es', 'Earth Science'), ('phy', 'Physics'), ('chem', 'Chemistry'), ('bio', 'Biography'), ('p&c', '理化'), ('prg', '程式'), ('art', 'Art'), ('oth', 'Others')], default='oth', max_length=10),
        ),
        migrations.CreateModel(
            name='Class_details',
            fields=[
                ('class_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=100)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('finish_or_not', models.BooleanField(default=False)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('class_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.class')),
            ],
        ),
        migrations.CreateModel(
            name='Class_DayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('class_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.class')),
            ],
        ),
    ]
