# Generated by Django 3.1.1 on 2020-10-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201025_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
