# Generated by Django 3.1.1 on 2021-02-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201025_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='card_number',
            new_name='bank_account',
        ),
        migrations.AddField(
            model_name='user',
            name='bank_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
