# Generated by Django 3.1.1 on 2021-02-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210220_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='pay_per_hour',
            new_name='pay_per_class',
        ),
        migrations.RemoveField(
            model_name='class',
            name='topic',
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, choices=[('mth', 'Math'), ('chn', 'Chinese'), ('eng', 'English'), ('geo', 'Geography'), ('his', 'History'), ('cvc', 'Civics'), ('scl', 'Social'), ('es', 'Earth Science'), ('phy', 'Physics'), ('chem', 'Chemistry'), ('bio', 'Biography'), ('pnc', 'PhyChem'), ('prg', 'Programming'), ('art', 'Art'), ('oth', 'Others')], default='oth', max_length=10),
        ),
    ]
