# Generated by Django 3.1.1 on 2021-02-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210224_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('trade_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trade_amt', models.IntegerField(blank=True, null=True)),
                ('trade_status', models.CharField(max_length=100)),
                ('trade_time', models.CharField(default='no record', max_length=100)),
                ('CheckMacValue', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='class_details',
            name='class_detail_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
