# Generated by Django 3.1.1 on 2021-03-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210227_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_details',
            name='class_detail_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
